[phases.setup]
nixPkgs = ["nodejs_20", "chromium", "glib", "nss", "nspr", "atk", "at-spi2-atk", "libdrm", "mesa", "libxkbcommon", "pango", "cairo", "alsa-lib"]

[phases.install]
cmds = ["npm install"]

[start]
cmd = "node server.js"
